{
 "title": "Viya Operations Dashboard",
 "tags": [ "sas-viya" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "NodeClass",
    "label": "Node Class",
    "query": {
     "query": "label_values(kube_node_labels,label_workload_sas_com_class)"
    }
   },
   {
    "name": "Node",
    "query": {
     "query": "label_values(kube_node_labels{label_workload_sas_com_class=~\"$NodeClass\"},node)"
    }
   },
   {
    "name": "Hidden",
    "label": "Hidden Container",
    "query": "pgbackrest|rabbitmq|sas-opendistro"
   }
  ]
 },
 "panels": [
  {
   "title": "Kubernetes Headroom",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resources by Node",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "count by (node) (kube_pod_info)",
       "legendFormat": "Pods"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"pods\"}) by (node)",
       "legendFormat": "Pods Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"cpu\"})\r by (node)",
       "legendFormat": "CPU Requested"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"cpu\"}) by (node)",
       "legendFormat": "CPU Allocatable"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (node)",
       "legendFormat": "Mem Requested"
      },
      {
       "expr": "sum(kube_node_status_capacity{resource=\"memory\"}) by (node)",
       "legendFormat": "Mem Allocatable"
      }
     ]
    }
   ]
  },
  {
   "title": "Perf / Node Utilization",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", nodename=~\"$Node\"}\n*\n  instance:node_num_cpu:sum{job=\"node-exporter\", nodename=~\"$Node\"}\n/ ignoring (instance) group_left\n  sum without (instance) (instance:node_num_cpu:sum{job=\"node-exporter\", nodename=~\"$Node\"})\n)\n",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "CPU Saturation (load1 per CPU)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  instance:node_load1_per_cpu:ratio{job=\"node-exporter\", nodename=~\"$Node\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_load1_per_cpu:ratio{job=\"node-exporter\", nodename=~\"$Node\"})\n)\n",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  instance:node_memory_utilisation:ratio{job=\"node-exporter\", nodename=~\"$Node\"}\n/ ignoring (instance) group_left\n  count without (instance) (instance:node_memory_utilisation:ratio{job=\"node-exporter\", nodename=~\"$Node\"})\n)\n",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Memory Saturation (Major Page Faults)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "rps" } },
     "targets": [
      {
       "expr": "instance:node_vmstat_pgmajfault:rate5m{job=\"node-exporter\", nodename=~\"$Node\"}",
       "legendFormat": "{{nodename}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Disk IO Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\", nodename=~\"$Node\" }\n/ ignoring (instance, device) group_left\n  count without (instance, device) (instance_device:node_disk_io_time_seconds:rate5m{job=\"node-exporter\", nodename=~\"$Node\"})\n)",
       "legendFormat": "{{nodename}} {{device}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Net Utilization (Bytes Receive/Transmit)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "instance:node_network_receive_bytes_excluding_lo:rate5m{job=\"node-exporter\", nodename=~\"$Node\"}",
       "legendFormat": "{{nodename}} Receive",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      },
      {
       "expr": "instance:node_network_transmit_bytes_excluding_lo:rate5m{job=\"node-exporter\", nodename=~\"$Node\"}",
       "legendFormat": "{{nodename}} Transmit",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Disk Capacity Used",
     "type": "timeseries",
     "description": "node local storage like ext4, xfs\nexcluding tmpfs & fuse.lxcfs",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "( sum without (device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", nodename=~\"$Node\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\"} \n    - node_filesystem_avail_bytes{job=\"node-exporter\", nodename=~\"$Node\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\"}\n    )\n  ) \n/ ignoring (instance) group_left\n  sum without (instance, device) (\n    max without () (\n      node_filesystem_size_bytes{job=\"node-exporter\", nodename=~\"$Node\", fstype!=\"tmpfs\", fstype!=\"fuse.lxcfs\"}\n    )\n  )\n)  ",
       "legendFormat": "{{nodename}}: {{mountpoint}} ({{fstype}})",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    },
    {
     "title": "Disk IO Saturation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\", nodename=~\"$Node\"}\n/ ignoring (instance, device) group_left\n  count without (instance, device) (instance_device:node_disk_io_time_weighted_seconds:rate5m{job=\"node-exporter\", nodename=~\"$Node\"})\n)\n",
       "legendFormat": "{{nodename}} {{device}}",
       "legendLink": "/dashboard/file/node-rsrc-use.json"
      }
     ]
    }
   ]
  },
  { "title": "Perf / Container Utilization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "% CPU use / lim",
   "type": "timeseries",
   "description": "100% (consider increasing req)\n0% (sized just right)\n-100% (consider decreasing req)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (irate(container_cpu_usage_seconds_total{job=\"kubelet\", container!~\"POD|$Hidden\", node=~\"$Node\", image!=\"\"}[4m])) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"cpu\", node=~\"$Node\", container!~\"$Hidden\"}) ))",
     "legendFormat": "{{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "% MEM use / lim",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "( 100 * (sum by(pod,container) (container_memory_usage_bytes{job=\"kubelet\", node=~\"$Node\", container!~\"POD|$Hidden\"}) / sum by(pod,container) (kube_pod_container_resource_limits{job=\"kube-state-metrics\", resource=\"memory\", node=~\"$Node\", container!~\"$Hidden\" }) ))\r\n",
     "legendFormat": "memUse/req: {{ container }}/{{pod}}"
    }
   ]
  },
  {
   "title": "Kubernetes / Persistent Volumes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Volume Space Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 *\n(\n  1 -\n  (\n    max by (namespace, persistentvolumeclaim)\n    (\n      kubelet_volume_stats_available_bytes{\n        job=\"kubelet\",\n        metrics_path=\"/metrics\"\n      }\n    )\n    /\n    max by (namespace, persistentvolumeclaim)\n    (\n      kubelet_volume_stats_capacity_bytes{\n        job=\"kubelet\",\n        metrics_path=\"/metrics\"\n      }\n    )\n  )\n)",
     "legendFormat": "{{namespace}}, {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "SAS Java Servcies",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "JVM Heap",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "100 *\r\n(\r\n  sum by (pod)\r\n    (jvm_memory_committed_bytes{job=~\".*\", pod=~\".*\", area=\"heap\"})\r\n/\r\n  sum by (pod)\r\n    (jvm_memory_max_bytes{job=~\".*\", pod=~\".*\", area=\"heap\"})\r\n)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ccp_connection_stats_max_connections{job=~\".*\"}",
       "legendFormat": "Max/{{instance}}"
      },
      {
       "expr": "ccp_connection_stats_active{job=~\".*\"}",
       "legendFormat": "Active/{{instance}}"
      },
      {
       "expr": "ccp_connection_stats_idle_in_txn{job=~\".*\"}",
       "legendFormat": "IdleTrn/{{instance}}"
      },
      {
       "expr": "ccp_connection_stats_idle{job=~\".*\"}",
       "legendFormat": "Idle/{{instance}}"
      }
     ]
    },
    {
     "title": "Replication Lag Time (Replica Only)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ccp_replication_lag_replay_time{job=~\".*\"}",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "OOM and restarts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 102 },
     "targets": [
      {
       "expr": "delta(kube_pod_container_status_restarts_total{namespace=~\".*\"}[1m])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "OOM killed processes per node delta",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
     "targets": [
      {
       "expr": "delta(node_vmstat_oom_kill[5m])",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  }
 ]
}